version: '3'

services: 
  test:
    container_name: test
    image: backend
    restart: always
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - CLOUDINARY_CLOUD_NAME=dwmsky6nu
      - CLOUDINARY_API_KEY=982366275336271
      - CLOUDINARY_API_SECRET=3xYTMjv3JNbDdHjXPZVeoF9DdA4
volumes:
  nps_data: {}